# Generated by Django 2.2.10 on 2020-05-12 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('type', models.CharField(choices=[('Text', 'Text'), ('One Option', 'One Option'), ('Many Options', 'Many Options')], default='Text', max_length=20)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Interview')),
            ],
        ),
    ]
