# Generated by Django 2.2.10 on 2020-05-12 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20200512_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Question')),
            ],
        ),
    ]
