# Generated by Django 2.2.10 on 2020-05-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20200512_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
